[package]
name = "dialoguer"
description = "A command line prompting library."
version = "0.3.0"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]
keywords = ["cli", "menu", "prompt"]
license = "MIT"
homepage = "https://github.com/mitsuhiko/dialoguer"
documentation = "https://docs.rs/dialoguer"
readme = "README.md"

[features]
default = ["validation"]
validation = ["regex"]

[dependencies]
console = ">=0.3.0, <1.0.0"
lazy_static = "1"
tempfile = "2"
regex = { version = "1.1.5", optional = true }
