[package]
name = "dialoguer"
description = "A command line prompting library."
version = "0.7.1"
edition = "2018"
authors = [
	"Armin Ronacher <armin.ronacher@active-4.com>",
	"Pavan Kumar Sunkara <pavan.sss1991@gmail.com>"
]
keywords = ["cli", "menu", "prompt"]
categories = ["command-line-interface"]
license = "MIT"
homepage = "https://github.com/mitsuhiko/dialoguer"
repository = "https://github.com/mitsuhiko/dialoguer"
documentation = "https://docs.rs/dialoguer"
readme = "README.md"

[dependencies]
console = "0.13.0"
lazy_static = "1"
tempfile = "3"
# `zeroize` of version "0.9.3" is used because it doesn't
# depend on `alloc` crate which is unstable for rustc 1.32.0
# which is currently the minimum supported version for `dialoguer`.
zeroize = { version = "0.9.3", default-features = false, features = ["std"] }
